-- Numbered migrations (newest first — add new lines at the top after each migration).
[x] 019_platform_key_grants.sql
[x] 018_ai_usage_cost_usd.sql
[x] 017_company_details.sql
[x] 016_companies.sql
[x] 015_note_contact.sql
[x] 014_user_directory.sql
[x] 013_contact_reach.sql
[x] 012_contact_names_he.sql
[x] 011_contact_names.sql
[x] 010_tag_colors.sql
[x] 009_ai.sql
[x] 008_tags.sql
[x] 007_event_previous_status.sql
[x] 006_job_statuses.sql
[x] 005_optional_follow_up.sql
[x] 004_entity_links.sql
[x] 003_event_starts_at.sql
[x] 002_flatten_notes.sql
[x] 001_initial_schema.sql
